// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

#include "telemetry.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_telemetry_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Feedback_telemetry_2eproto;
namespace telemetry {
class FeedbackDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Feedback> _instance;
} _Feedback_default_instance_;
class TelemetryRecordDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TelemetryRecord> _instance;
} _TelemetryRecord_default_instance_;
}  // namespace telemetry
static void InitDefaultsscc_info_Feedback_telemetry_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::telemetry::_Feedback_default_instance_;
    new (ptr) ::telemetry::Feedback();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::telemetry::Feedback::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Feedback_telemetry_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Feedback_telemetry_2eproto}, {}};

static void InitDefaultsscc_info_TelemetryRecord_telemetry_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::telemetry::_TelemetryRecord_default_instance_;
    new (ptr) ::telemetry::TelemetryRecord();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::telemetry::TelemetryRecord::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_TelemetryRecord_telemetry_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_TelemetryRecord_telemetry_2eproto}, {
      &scc_info_Feedback_telemetry_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_telemetry_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_telemetry_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_telemetry_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_telemetry_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::telemetry::Feedback, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::telemetry::Feedback, timeusec_),
  PROTOBUF_FIELD_OFFSET(::telemetry::Feedback, imgidx_),
  PROTOBUF_FIELD_OFFSET(::telemetry::Feedback, lat_),
  PROTOBUF_FIELD_OFFSET(::telemetry::Feedback, lng_),
  PROTOBUF_FIELD_OFFSET(::telemetry::Feedback, altmsl_),
  PROTOBUF_FIELD_OFFSET(::telemetry::Feedback, altrel_),
  PROTOBUF_FIELD_OFFSET(::telemetry::Feedback, roll_),
  PROTOBUF_FIELD_OFFSET(::telemetry::Feedback, pitch_),
  PROTOBUF_FIELD_OFFSET(::telemetry::Feedback, yaw_),
  PROTOBUF_FIELD_OFFSET(::telemetry::Feedback, completedcaptures_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::telemetry::TelemetryRecord, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::telemetry::TelemetryRecord, timeus_),
  PROTOBUF_FIELD_OFFSET(::telemetry::TelemetryRecord, img_),
  PROTOBUF_FIELD_OFFSET(::telemetry::TelemetryRecord, path_),
  PROTOBUF_FIELD_OFFSET(::telemetry::TelemetryRecord, epoch_),
  PROTOBUF_FIELD_OFFSET(::telemetry::TelemetryRecord, deltat_),
  PROTOBUF_FIELD_OFFSET(::telemetry::TelemetryRecord, feedback_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::telemetry::Feedback)},
  { 15, -1, sizeof(::telemetry::TelemetryRecord)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::telemetry::_Feedback_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::telemetry::_TelemetryRecord_default_instance_),
};

const char descriptor_table_protodef_telemetry_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017telemetry.proto\022\ttelemetry\"\253\001\n\010Feedbac"
  "k\022\020\n\010timeUsec\030\001 \001(\004\022\016\n\006imgIdx\030\002 \001(\r\022\013\n\003l"
  "at\030\003 \001(\005\022\013\n\003lng\030\004 \001(\005\022\016\n\006altMsl\030\005 \001(\002\022\016\n"
  "\006altRel\030\006 \001(\002\022\014\n\004roll\030\007 \001(\002\022\r\n\005pitch\030\010 \001"
  "(\002\022\013\n\003yaw\030\t \001(\002\022\031\n\021completedCaptures\030\n \001"
  "(\r\"\202\001\n\017TelemetryRecord\022\016\n\006timeUs\030\001 \001(\004\022\013"
  "\n\003img\030\002 \001(\004\022\014\n\004path\030\003 \001(\t\022\r\n\005epoch\030\004 \001(\004"
  "\022\016\n\006deltaT\030\005 \001(\003\022%\n\010feedback\030\006 \001(\0132\023.tel"
  "emetry.Feedbackb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_telemetry_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_telemetry_2eproto_sccs[2] = {
  &scc_info_Feedback_telemetry_2eproto.base,
  &scc_info_TelemetryRecord_telemetry_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_telemetry_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_telemetry_2eproto = {
  false, false, descriptor_table_protodef_telemetry_2eproto, "telemetry.proto", 343,
  &descriptor_table_telemetry_2eproto_once, descriptor_table_telemetry_2eproto_sccs, descriptor_table_telemetry_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_telemetry_2eproto::offsets,
  file_level_metadata_telemetry_2eproto, 2, file_level_enum_descriptors_telemetry_2eproto, file_level_service_descriptors_telemetry_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_telemetry_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_telemetry_2eproto)), true);
namespace telemetry {

// ===================================================================

void Feedback::InitAsDefaultInstance() {
}
class Feedback::_Internal {
 public:
};

Feedback::Feedback(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:telemetry.Feedback)
}
Feedback::Feedback(const Feedback& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&timeusec_, &from.timeusec_,
    static_cast<size_t>(reinterpret_cast<char*>(&completedcaptures_) -
    reinterpret_cast<char*>(&timeusec_)) + sizeof(completedcaptures_));
  // @@protoc_insertion_point(copy_constructor:telemetry.Feedback)
}

void Feedback::SharedCtor() {
  ::memset(&timeusec_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&completedcaptures_) -
      reinterpret_cast<char*>(&timeusec_)) + sizeof(completedcaptures_));
}

Feedback::~Feedback() {
  // @@protoc_insertion_point(destructor:telemetry.Feedback)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Feedback::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Feedback::ArenaDtor(void* object) {
  Feedback* _this = reinterpret_cast< Feedback* >(object);
  (void)_this;
}
void Feedback::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Feedback::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Feedback& Feedback::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Feedback_telemetry_2eproto.base);
  return *internal_default_instance();
}


void Feedback::Clear() {
// @@protoc_insertion_point(message_clear_start:telemetry.Feedback)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&timeusec_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&completedcaptures_) -
      reinterpret_cast<char*>(&timeusec_)) + sizeof(completedcaptures_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Feedback::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint64 timeUsec = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          timeusec_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 imgIdx = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          imgidx_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 lat = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          lat_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 lng = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          lng_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float altMsl = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 45)) {
          altmsl_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float altRel = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 53)) {
          altrel_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float roll = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 61)) {
          roll_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float pitch = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 69)) {
          pitch_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float yaw = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 77)) {
          yaw_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // uint32 completedCaptures = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 80)) {
          completedcaptures_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Feedback::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:telemetry.Feedback)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 timeUsec = 1;
  if (this->timeusec() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_timeusec(), target);
  }

  // uint32 imgIdx = 2;
  if (this->imgidx() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_imgidx(), target);
  }

  // int32 lat = 3;
  if (this->lat() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_lat(), target);
  }

  // int32 lng = 4;
  if (this->lng() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_lng(), target);
  }

  // float altMsl = 5;
  if (!(this->altmsl() <= 0 && this->altmsl() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(5, this->_internal_altmsl(), target);
  }

  // float altRel = 6;
  if (!(this->altrel() <= 0 && this->altrel() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(6, this->_internal_altrel(), target);
  }

  // float roll = 7;
  if (!(this->roll() <= 0 && this->roll() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(7, this->_internal_roll(), target);
  }

  // float pitch = 8;
  if (!(this->pitch() <= 0 && this->pitch() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(8, this->_internal_pitch(), target);
  }

  // float yaw = 9;
  if (!(this->yaw() <= 0 && this->yaw() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(9, this->_internal_yaw(), target);
  }

  // uint32 completedCaptures = 10;
  if (this->completedcaptures() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(10, this->_internal_completedcaptures(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:telemetry.Feedback)
  return target;
}

size_t Feedback::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:telemetry.Feedback)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 timeUsec = 1;
  if (this->timeusec() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_timeusec());
  }

  // uint32 imgIdx = 2;
  if (this->imgidx() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_imgidx());
  }

  // int32 lat = 3;
  if (this->lat() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_lat());
  }

  // int32 lng = 4;
  if (this->lng() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_lng());
  }

  // float altMsl = 5;
  if (!(this->altmsl() <= 0 && this->altmsl() >= 0)) {
    total_size += 1 + 4;
  }

  // float altRel = 6;
  if (!(this->altrel() <= 0 && this->altrel() >= 0)) {
    total_size += 1 + 4;
  }

  // float roll = 7;
  if (!(this->roll() <= 0 && this->roll() >= 0)) {
    total_size += 1 + 4;
  }

  // float pitch = 8;
  if (!(this->pitch() <= 0 && this->pitch() >= 0)) {
    total_size += 1 + 4;
  }

  // float yaw = 9;
  if (!(this->yaw() <= 0 && this->yaw() >= 0)) {
    total_size += 1 + 4;
  }

  // uint32 completedCaptures = 10;
  if (this->completedcaptures() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_completedcaptures());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Feedback::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:telemetry.Feedback)
  GOOGLE_DCHECK_NE(&from, this);
  const Feedback* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Feedback>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:telemetry.Feedback)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:telemetry.Feedback)
    MergeFrom(*source);
  }
}

void Feedback::MergeFrom(const Feedback& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:telemetry.Feedback)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.timeusec() != 0) {
    _internal_set_timeusec(from._internal_timeusec());
  }
  if (from.imgidx() != 0) {
    _internal_set_imgidx(from._internal_imgidx());
  }
  if (from.lat() != 0) {
    _internal_set_lat(from._internal_lat());
  }
  if (from.lng() != 0) {
    _internal_set_lng(from._internal_lng());
  }
  if (!(from.altmsl() <= 0 && from.altmsl() >= 0)) {
    _internal_set_altmsl(from._internal_altmsl());
  }
  if (!(from.altrel() <= 0 && from.altrel() >= 0)) {
    _internal_set_altrel(from._internal_altrel());
  }
  if (!(from.roll() <= 0 && from.roll() >= 0)) {
    _internal_set_roll(from._internal_roll());
  }
  if (!(from.pitch() <= 0 && from.pitch() >= 0)) {
    _internal_set_pitch(from._internal_pitch());
  }
  if (!(from.yaw() <= 0 && from.yaw() >= 0)) {
    _internal_set_yaw(from._internal_yaw());
  }
  if (from.completedcaptures() != 0) {
    _internal_set_completedcaptures(from._internal_completedcaptures());
  }
}

void Feedback::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:telemetry.Feedback)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Feedback::CopyFrom(const Feedback& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:telemetry.Feedback)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Feedback::IsInitialized() const {
  return true;
}

void Feedback::InternalSwap(Feedback* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Feedback, completedcaptures_)
      + sizeof(Feedback::completedcaptures_)
      - PROTOBUF_FIELD_OFFSET(Feedback, timeusec_)>(
          reinterpret_cast<char*>(&timeusec_),
          reinterpret_cast<char*>(&other->timeusec_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Feedback::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void TelemetryRecord::InitAsDefaultInstance() {
  ::telemetry::_TelemetryRecord_default_instance_._instance.get_mutable()->feedback_ = const_cast< ::telemetry::Feedback*>(
      ::telemetry::Feedback::internal_default_instance());
}
class TelemetryRecord::_Internal {
 public:
  static const ::telemetry::Feedback& feedback(const TelemetryRecord* msg);
};

const ::telemetry::Feedback&
TelemetryRecord::_Internal::feedback(const TelemetryRecord* msg) {
  return *msg->feedback_;
}
TelemetryRecord::TelemetryRecord(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:telemetry.TelemetryRecord)
}
TelemetryRecord::TelemetryRecord(const TelemetryRecord& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_path().empty()) {
    path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_path(),
      GetArena());
  }
  if (from._internal_has_feedback()) {
    feedback_ = new ::telemetry::Feedback(*from.feedback_);
  } else {
    feedback_ = nullptr;
  }
  ::memcpy(&timeus_, &from.timeus_,
    static_cast<size_t>(reinterpret_cast<char*>(&deltat_) -
    reinterpret_cast<char*>(&timeus_)) + sizeof(deltat_));
  // @@protoc_insertion_point(copy_constructor:telemetry.TelemetryRecord)
}

void TelemetryRecord::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_TelemetryRecord_telemetry_2eproto.base);
  path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&feedback_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&deltat_) -
      reinterpret_cast<char*>(&feedback_)) + sizeof(deltat_));
}

TelemetryRecord::~TelemetryRecord() {
  // @@protoc_insertion_point(destructor:telemetry.TelemetryRecord)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void TelemetryRecord::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  path_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete feedback_;
}

void TelemetryRecord::ArenaDtor(void* object) {
  TelemetryRecord* _this = reinterpret_cast< TelemetryRecord* >(object);
  (void)_this;
}
void TelemetryRecord::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TelemetryRecord::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TelemetryRecord& TelemetryRecord::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TelemetryRecord_telemetry_2eproto.base);
  return *internal_default_instance();
}


void TelemetryRecord::Clear() {
// @@protoc_insertion_point(message_clear_start:telemetry.TelemetryRecord)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  path_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  if (GetArena() == nullptr && feedback_ != nullptr) {
    delete feedback_;
  }
  feedback_ = nullptr;
  ::memset(&timeus_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&deltat_) -
      reinterpret_cast<char*>(&timeus_)) + sizeof(deltat_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TelemetryRecord::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint64 timeUs = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          timeus_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 img = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          img_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string path = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_path();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "telemetry.TelemetryRecord.path"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 epoch = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          epoch_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 deltaT = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          deltat_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .telemetry.Feedback feedback = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_feedback(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TelemetryRecord::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:telemetry.TelemetryRecord)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 timeUs = 1;
  if (this->timeus() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_timeus(), target);
  }

  // uint64 img = 2;
  if (this->img() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(2, this->_internal_img(), target);
  }

  // string path = 3;
  if (this->path().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_path().data(), static_cast<int>(this->_internal_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "telemetry.TelemetryRecord.path");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_path(), target);
  }

  // uint64 epoch = 4;
  if (this->epoch() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(4, this->_internal_epoch(), target);
  }

  // int64 deltaT = 5;
  if (this->deltat() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(5, this->_internal_deltat(), target);
  }

  // .telemetry.Feedback feedback = 6;
  if (this->has_feedback()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        6, _Internal::feedback(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:telemetry.TelemetryRecord)
  return target;
}

size_t TelemetryRecord::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:telemetry.TelemetryRecord)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string path = 3;
  if (this->path().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_path());
  }

  // .telemetry.Feedback feedback = 6;
  if (this->has_feedback()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *feedback_);
  }

  // uint64 timeUs = 1;
  if (this->timeus() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_timeus());
  }

  // uint64 img = 2;
  if (this->img() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_img());
  }

  // uint64 epoch = 4;
  if (this->epoch() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_epoch());
  }

  // int64 deltaT = 5;
  if (this->deltat() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_deltat());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TelemetryRecord::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:telemetry.TelemetryRecord)
  GOOGLE_DCHECK_NE(&from, this);
  const TelemetryRecord* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TelemetryRecord>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:telemetry.TelemetryRecord)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:telemetry.TelemetryRecord)
    MergeFrom(*source);
  }
}

void TelemetryRecord::MergeFrom(const TelemetryRecord& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:telemetry.TelemetryRecord)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.path().size() > 0) {
    _internal_set_path(from._internal_path());
  }
  if (from.has_feedback()) {
    _internal_mutable_feedback()->::telemetry::Feedback::MergeFrom(from._internal_feedback());
  }
  if (from.timeus() != 0) {
    _internal_set_timeus(from._internal_timeus());
  }
  if (from.img() != 0) {
    _internal_set_img(from._internal_img());
  }
  if (from.epoch() != 0) {
    _internal_set_epoch(from._internal_epoch());
  }
  if (from.deltat() != 0) {
    _internal_set_deltat(from._internal_deltat());
  }
}

void TelemetryRecord::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:telemetry.TelemetryRecord)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TelemetryRecord::CopyFrom(const TelemetryRecord& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:telemetry.TelemetryRecord)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TelemetryRecord::IsInitialized() const {
  return true;
}

void TelemetryRecord::InternalSwap(TelemetryRecord* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  path_.Swap(&other->path_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TelemetryRecord, deltat_)
      + sizeof(TelemetryRecord::deltat_)
      - PROTOBUF_FIELD_OFFSET(TelemetryRecord, feedback_)>(
          reinterpret_cast<char*>(&feedback_),
          reinterpret_cast<char*>(&other->feedback_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TelemetryRecord::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace telemetry
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::telemetry::Feedback* Arena::CreateMaybeMessage< ::telemetry::Feedback >(Arena* arena) {
  return Arena::CreateMessageInternal< ::telemetry::Feedback >(arena);
}
template<> PROTOBUF_NOINLINE ::telemetry::TelemetryRecord* Arena::CreateMaybeMessage< ::telemetry::TelemetryRecord >(Arena* arena) {
  return Arena::CreateMessageInternal< ::telemetry::TelemetryRecord >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
