// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_telemetry_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_telemetry_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_telemetry_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_telemetry_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_telemetry_2eproto;
namespace telemetry {
class Feedback;
class FeedbackDefaultTypeInternal;
extern FeedbackDefaultTypeInternal _Feedback_default_instance_;
class TelemetryRecord;
class TelemetryRecordDefaultTypeInternal;
extern TelemetryRecordDefaultTypeInternal _TelemetryRecord_default_instance_;
}  // namespace telemetry
PROTOBUF_NAMESPACE_OPEN
template<> ::telemetry::Feedback* Arena::CreateMaybeMessage<::telemetry::Feedback>(Arena*);
template<> ::telemetry::TelemetryRecord* Arena::CreateMaybeMessage<::telemetry::TelemetryRecord>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace telemetry {

// ===================================================================

class Feedback PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:telemetry.Feedback) */ {
 public:
  inline Feedback() : Feedback(nullptr) {};
  virtual ~Feedback();

  Feedback(const Feedback& from);
  Feedback(Feedback&& from) noexcept
    : Feedback() {
    *this = ::std::move(from);
  }

  inline Feedback& operator=(const Feedback& from) {
    CopyFrom(from);
    return *this;
  }
  inline Feedback& operator=(Feedback&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Feedback& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Feedback* internal_default_instance() {
    return reinterpret_cast<const Feedback*>(
               &_Feedback_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Feedback& a, Feedback& b) {
    a.Swap(&b);
  }
  inline void Swap(Feedback* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Feedback* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Feedback* New() const final {
    return CreateMaybeMessage<Feedback>(nullptr);
  }

  Feedback* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Feedback>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Feedback& from);
  void MergeFrom(const Feedback& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Feedback* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "telemetry.Feedback";
  }
  protected:
  explicit Feedback(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_telemetry_2eproto);
    return ::descriptor_table_telemetry_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimeUsecFieldNumber = 1,
    kImgIdxFieldNumber = 2,
    kLatFieldNumber = 3,
    kLngFieldNumber = 4,
    kAltMslFieldNumber = 5,
    kAltRelFieldNumber = 6,
    kRollFieldNumber = 7,
    kPitchFieldNumber = 8,
    kYawFieldNumber = 9,
    kCompletedCapturesFieldNumber = 10,
  };
  // uint64 timeUsec = 1;
  void clear_timeusec();
  ::PROTOBUF_NAMESPACE_ID::uint64 timeusec() const;
  void set_timeusec(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timeusec() const;
  void _internal_set_timeusec(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 imgIdx = 2;
  void clear_imgidx();
  ::PROTOBUF_NAMESPACE_ID::uint32 imgidx() const;
  void set_imgidx(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_imgidx() const;
  void _internal_set_imgidx(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // int32 lat = 3;
  void clear_lat();
  ::PROTOBUF_NAMESPACE_ID::int32 lat() const;
  void set_lat(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_lat() const;
  void _internal_set_lat(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 lng = 4;
  void clear_lng();
  ::PROTOBUF_NAMESPACE_ID::int32 lng() const;
  void set_lng(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_lng() const;
  void _internal_set_lng(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // float altMsl = 5;
  void clear_altmsl();
  float altmsl() const;
  void set_altmsl(float value);
  private:
  float _internal_altmsl() const;
  void _internal_set_altmsl(float value);
  public:

  // float altRel = 6;
  void clear_altrel();
  float altrel() const;
  void set_altrel(float value);
  private:
  float _internal_altrel() const;
  void _internal_set_altrel(float value);
  public:

  // float roll = 7;
  void clear_roll();
  float roll() const;
  void set_roll(float value);
  private:
  float _internal_roll() const;
  void _internal_set_roll(float value);
  public:

  // float pitch = 8;
  void clear_pitch();
  float pitch() const;
  void set_pitch(float value);
  private:
  float _internal_pitch() const;
  void _internal_set_pitch(float value);
  public:

  // float yaw = 9;
  void clear_yaw();
  float yaw() const;
  void set_yaw(float value);
  private:
  float _internal_yaw() const;
  void _internal_set_yaw(float value);
  public:

  // uint32 completedCaptures = 10;
  void clear_completedcaptures();
  ::PROTOBUF_NAMESPACE_ID::uint32 completedcaptures() const;
  void set_completedcaptures(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_completedcaptures() const;
  void _internal_set_completedcaptures(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:telemetry.Feedback)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timeusec_;
  ::PROTOBUF_NAMESPACE_ID::uint32 imgidx_;
  ::PROTOBUF_NAMESPACE_ID::int32 lat_;
  ::PROTOBUF_NAMESPACE_ID::int32 lng_;
  float altmsl_;
  float altrel_;
  float roll_;
  float pitch_;
  float yaw_;
  ::PROTOBUF_NAMESPACE_ID::uint32 completedcaptures_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_telemetry_2eproto;
};
// -------------------------------------------------------------------

class TelemetryRecord PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:telemetry.TelemetryRecord) */ {
 public:
  inline TelemetryRecord() : TelemetryRecord(nullptr) {};
  virtual ~TelemetryRecord();

  TelemetryRecord(const TelemetryRecord& from);
  TelemetryRecord(TelemetryRecord&& from) noexcept
    : TelemetryRecord() {
    *this = ::std::move(from);
  }

  inline TelemetryRecord& operator=(const TelemetryRecord& from) {
    CopyFrom(from);
    return *this;
  }
  inline TelemetryRecord& operator=(TelemetryRecord&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TelemetryRecord& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TelemetryRecord* internal_default_instance() {
    return reinterpret_cast<const TelemetryRecord*>(
               &_TelemetryRecord_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TelemetryRecord& a, TelemetryRecord& b) {
    a.Swap(&b);
  }
  inline void Swap(TelemetryRecord* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TelemetryRecord* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TelemetryRecord* New() const final {
    return CreateMaybeMessage<TelemetryRecord>(nullptr);
  }

  TelemetryRecord* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TelemetryRecord>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TelemetryRecord& from);
  void MergeFrom(const TelemetryRecord& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TelemetryRecord* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "telemetry.TelemetryRecord";
  }
  protected:
  explicit TelemetryRecord(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_telemetry_2eproto);
    return ::descriptor_table_telemetry_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPathFieldNumber = 3,
    kFeedbackFieldNumber = 6,
    kTimeUsFieldNumber = 1,
    kImgFieldNumber = 2,
    kEpochFieldNumber = 4,
    kDeltaTFieldNumber = 5,
  };
  // string path = 3;
  void clear_path();
  const std::string& path() const;
  void set_path(const std::string& value);
  void set_path(std::string&& value);
  void set_path(const char* value);
  void set_path(const char* value, size_t size);
  std::string* mutable_path();
  std::string* release_path();
  void set_allocated_path(std::string* path);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_path();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_path(
      std::string* path);
  private:
  const std::string& _internal_path() const;
  void _internal_set_path(const std::string& value);
  std::string* _internal_mutable_path();
  public:

  // .telemetry.Feedback feedback = 6;
  bool has_feedback() const;
  private:
  bool _internal_has_feedback() const;
  public:
  void clear_feedback();
  const ::telemetry::Feedback& feedback() const;
  ::telemetry::Feedback* release_feedback();
  ::telemetry::Feedback* mutable_feedback();
  void set_allocated_feedback(::telemetry::Feedback* feedback);
  private:
  const ::telemetry::Feedback& _internal_feedback() const;
  ::telemetry::Feedback* _internal_mutable_feedback();
  public:
  void unsafe_arena_set_allocated_feedback(
      ::telemetry::Feedback* feedback);
  ::telemetry::Feedback* unsafe_arena_release_feedback();

  // uint64 timeUs = 1;
  void clear_timeus();
  ::PROTOBUF_NAMESPACE_ID::uint64 timeus() const;
  void set_timeus(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timeus() const;
  void _internal_set_timeus(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 img = 2;
  void clear_img();
  ::PROTOBUF_NAMESPACE_ID::uint64 img() const;
  void set_img(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_img() const;
  void _internal_set_img(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 epoch = 4;
  void clear_epoch();
  ::PROTOBUF_NAMESPACE_ID::uint64 epoch() const;
  void set_epoch(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_epoch() const;
  void _internal_set_epoch(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // int64 deltaT = 5;
  void clear_deltat();
  ::PROTOBUF_NAMESPACE_ID::int64 deltat() const;
  void set_deltat(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_deltat() const;
  void _internal_set_deltat(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:telemetry.TelemetryRecord)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_;
  ::telemetry::Feedback* feedback_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timeus_;
  ::PROTOBUF_NAMESPACE_ID::uint64 img_;
  ::PROTOBUF_NAMESPACE_ID::uint64 epoch_;
  ::PROTOBUF_NAMESPACE_ID::int64 deltat_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_telemetry_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Feedback

// uint64 timeUsec = 1;
inline void Feedback::clear_timeusec() {
  timeusec_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Feedback::_internal_timeusec() const {
  return timeusec_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Feedback::timeusec() const {
  // @@protoc_insertion_point(field_get:telemetry.Feedback.timeUsec)
  return _internal_timeusec();
}
inline void Feedback::_internal_set_timeusec(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  timeusec_ = value;
}
inline void Feedback::set_timeusec(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timeusec(value);
  // @@protoc_insertion_point(field_set:telemetry.Feedback.timeUsec)
}

// uint32 imgIdx = 2;
inline void Feedback::clear_imgidx() {
  imgidx_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Feedback::_internal_imgidx() const {
  return imgidx_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Feedback::imgidx() const {
  // @@protoc_insertion_point(field_get:telemetry.Feedback.imgIdx)
  return _internal_imgidx();
}
inline void Feedback::_internal_set_imgidx(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  imgidx_ = value;
}
inline void Feedback::set_imgidx(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_imgidx(value);
  // @@protoc_insertion_point(field_set:telemetry.Feedback.imgIdx)
}

// int32 lat = 3;
inline void Feedback::clear_lat() {
  lat_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Feedback::_internal_lat() const {
  return lat_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Feedback::lat() const {
  // @@protoc_insertion_point(field_get:telemetry.Feedback.lat)
  return _internal_lat();
}
inline void Feedback::_internal_set_lat(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  lat_ = value;
}
inline void Feedback::set_lat(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_lat(value);
  // @@protoc_insertion_point(field_set:telemetry.Feedback.lat)
}

// int32 lng = 4;
inline void Feedback::clear_lng() {
  lng_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Feedback::_internal_lng() const {
  return lng_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Feedback::lng() const {
  // @@protoc_insertion_point(field_get:telemetry.Feedback.lng)
  return _internal_lng();
}
inline void Feedback::_internal_set_lng(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  lng_ = value;
}
inline void Feedback::set_lng(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_lng(value);
  // @@protoc_insertion_point(field_set:telemetry.Feedback.lng)
}

// float altMsl = 5;
inline void Feedback::clear_altmsl() {
  altmsl_ = 0;
}
inline float Feedback::_internal_altmsl() const {
  return altmsl_;
}
inline float Feedback::altmsl() const {
  // @@protoc_insertion_point(field_get:telemetry.Feedback.altMsl)
  return _internal_altmsl();
}
inline void Feedback::_internal_set_altmsl(float value) {
  
  altmsl_ = value;
}
inline void Feedback::set_altmsl(float value) {
  _internal_set_altmsl(value);
  // @@protoc_insertion_point(field_set:telemetry.Feedback.altMsl)
}

// float altRel = 6;
inline void Feedback::clear_altrel() {
  altrel_ = 0;
}
inline float Feedback::_internal_altrel() const {
  return altrel_;
}
inline float Feedback::altrel() const {
  // @@protoc_insertion_point(field_get:telemetry.Feedback.altRel)
  return _internal_altrel();
}
inline void Feedback::_internal_set_altrel(float value) {
  
  altrel_ = value;
}
inline void Feedback::set_altrel(float value) {
  _internal_set_altrel(value);
  // @@protoc_insertion_point(field_set:telemetry.Feedback.altRel)
}

// float roll = 7;
inline void Feedback::clear_roll() {
  roll_ = 0;
}
inline float Feedback::_internal_roll() const {
  return roll_;
}
inline float Feedback::roll() const {
  // @@protoc_insertion_point(field_get:telemetry.Feedback.roll)
  return _internal_roll();
}
inline void Feedback::_internal_set_roll(float value) {
  
  roll_ = value;
}
inline void Feedback::set_roll(float value) {
  _internal_set_roll(value);
  // @@protoc_insertion_point(field_set:telemetry.Feedback.roll)
}

// float pitch = 8;
inline void Feedback::clear_pitch() {
  pitch_ = 0;
}
inline float Feedback::_internal_pitch() const {
  return pitch_;
}
inline float Feedback::pitch() const {
  // @@protoc_insertion_point(field_get:telemetry.Feedback.pitch)
  return _internal_pitch();
}
inline void Feedback::_internal_set_pitch(float value) {
  
  pitch_ = value;
}
inline void Feedback::set_pitch(float value) {
  _internal_set_pitch(value);
  // @@protoc_insertion_point(field_set:telemetry.Feedback.pitch)
}

// float yaw = 9;
inline void Feedback::clear_yaw() {
  yaw_ = 0;
}
inline float Feedback::_internal_yaw() const {
  return yaw_;
}
inline float Feedback::yaw() const {
  // @@protoc_insertion_point(field_get:telemetry.Feedback.yaw)
  return _internal_yaw();
}
inline void Feedback::_internal_set_yaw(float value) {
  
  yaw_ = value;
}
inline void Feedback::set_yaw(float value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:telemetry.Feedback.yaw)
}

// uint32 completedCaptures = 10;
inline void Feedback::clear_completedcaptures() {
  completedcaptures_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Feedback::_internal_completedcaptures() const {
  return completedcaptures_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Feedback::completedcaptures() const {
  // @@protoc_insertion_point(field_get:telemetry.Feedback.completedCaptures)
  return _internal_completedcaptures();
}
inline void Feedback::_internal_set_completedcaptures(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  completedcaptures_ = value;
}
inline void Feedback::set_completedcaptures(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_completedcaptures(value);
  // @@protoc_insertion_point(field_set:telemetry.Feedback.completedCaptures)
}

// -------------------------------------------------------------------

// TelemetryRecord

// uint64 timeUs = 1;
inline void TelemetryRecord::clear_timeus() {
  timeus_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TelemetryRecord::_internal_timeus() const {
  return timeus_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TelemetryRecord::timeus() const {
  // @@protoc_insertion_point(field_get:telemetry.TelemetryRecord.timeUs)
  return _internal_timeus();
}
inline void TelemetryRecord::_internal_set_timeus(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  timeus_ = value;
}
inline void TelemetryRecord::set_timeus(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timeus(value);
  // @@protoc_insertion_point(field_set:telemetry.TelemetryRecord.timeUs)
}

// uint64 img = 2;
inline void TelemetryRecord::clear_img() {
  img_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TelemetryRecord::_internal_img() const {
  return img_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TelemetryRecord::img() const {
  // @@protoc_insertion_point(field_get:telemetry.TelemetryRecord.img)
  return _internal_img();
}
inline void TelemetryRecord::_internal_set_img(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  img_ = value;
}
inline void TelemetryRecord::set_img(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_img(value);
  // @@protoc_insertion_point(field_set:telemetry.TelemetryRecord.img)
}

// string path = 3;
inline void TelemetryRecord::clear_path() {
  path_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& TelemetryRecord::path() const {
  // @@protoc_insertion_point(field_get:telemetry.TelemetryRecord.path)
  return _internal_path();
}
inline void TelemetryRecord::set_path(const std::string& value) {
  _internal_set_path(value);
  // @@protoc_insertion_point(field_set:telemetry.TelemetryRecord.path)
}
inline std::string* TelemetryRecord::mutable_path() {
  // @@protoc_insertion_point(field_mutable:telemetry.TelemetryRecord.path)
  return _internal_mutable_path();
}
inline const std::string& TelemetryRecord::_internal_path() const {
  return path_.Get();
}
inline void TelemetryRecord::_internal_set_path(const std::string& value) {
  
  path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void TelemetryRecord::set_path(std::string&& value) {
  
  path_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:telemetry.TelemetryRecord.path)
}
inline void TelemetryRecord::set_path(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:telemetry.TelemetryRecord.path)
}
inline void TelemetryRecord::set_path(const char* value,
    size_t size) {
  
  path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:telemetry.TelemetryRecord.path)
}
inline std::string* TelemetryRecord::_internal_mutable_path() {
  
  return path_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* TelemetryRecord::release_path() {
  // @@protoc_insertion_point(field_release:telemetry.TelemetryRecord.path)
  return path_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TelemetryRecord::set_allocated_path(std::string* path) {
  if (path != nullptr) {
    
  } else {
    
  }
  path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:telemetry.TelemetryRecord.path)
}
inline std::string* TelemetryRecord::unsafe_arena_release_path() {
  // @@protoc_insertion_point(field_unsafe_arena_release:telemetry.TelemetryRecord.path)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return path_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void TelemetryRecord::unsafe_arena_set_allocated_path(
    std::string* path) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (path != nullptr) {
    
  } else {
    
  }
  path_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      path, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:telemetry.TelemetryRecord.path)
}

// uint64 epoch = 4;
inline void TelemetryRecord::clear_epoch() {
  epoch_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TelemetryRecord::_internal_epoch() const {
  return epoch_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TelemetryRecord::epoch() const {
  // @@protoc_insertion_point(field_get:telemetry.TelemetryRecord.epoch)
  return _internal_epoch();
}
inline void TelemetryRecord::_internal_set_epoch(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  epoch_ = value;
}
inline void TelemetryRecord::set_epoch(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_epoch(value);
  // @@protoc_insertion_point(field_set:telemetry.TelemetryRecord.epoch)
}

// int64 deltaT = 5;
inline void TelemetryRecord::clear_deltat() {
  deltat_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TelemetryRecord::_internal_deltat() const {
  return deltat_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TelemetryRecord::deltat() const {
  // @@protoc_insertion_point(field_get:telemetry.TelemetryRecord.deltaT)
  return _internal_deltat();
}
inline void TelemetryRecord::_internal_set_deltat(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  deltat_ = value;
}
inline void TelemetryRecord::set_deltat(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_deltat(value);
  // @@protoc_insertion_point(field_set:telemetry.TelemetryRecord.deltaT)
}

// .telemetry.Feedback feedback = 6;
inline bool TelemetryRecord::_internal_has_feedback() const {
  return this != internal_default_instance() && feedback_ != nullptr;
}
inline bool TelemetryRecord::has_feedback() const {
  return _internal_has_feedback();
}
inline void TelemetryRecord::clear_feedback() {
  if (GetArena() == nullptr && feedback_ != nullptr) {
    delete feedback_;
  }
  feedback_ = nullptr;
}
inline const ::telemetry::Feedback& TelemetryRecord::_internal_feedback() const {
  const ::telemetry::Feedback* p = feedback_;
  return p != nullptr ? *p : *reinterpret_cast<const ::telemetry::Feedback*>(
      &::telemetry::_Feedback_default_instance_);
}
inline const ::telemetry::Feedback& TelemetryRecord::feedback() const {
  // @@protoc_insertion_point(field_get:telemetry.TelemetryRecord.feedback)
  return _internal_feedback();
}
inline void TelemetryRecord::unsafe_arena_set_allocated_feedback(
    ::telemetry::Feedback* feedback) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(feedback_);
  }
  feedback_ = feedback;
  if (feedback) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:telemetry.TelemetryRecord.feedback)
}
inline ::telemetry::Feedback* TelemetryRecord::release_feedback() {
  auto temp = unsafe_arena_release_feedback();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::telemetry::Feedback* TelemetryRecord::unsafe_arena_release_feedback() {
  // @@protoc_insertion_point(field_release:telemetry.TelemetryRecord.feedback)
  
  ::telemetry::Feedback* temp = feedback_;
  feedback_ = nullptr;
  return temp;
}
inline ::telemetry::Feedback* TelemetryRecord::_internal_mutable_feedback() {
  
  if (feedback_ == nullptr) {
    auto* p = CreateMaybeMessage<::telemetry::Feedback>(GetArena());
    feedback_ = p;
  }
  return feedback_;
}
inline ::telemetry::Feedback* TelemetryRecord::mutable_feedback() {
  // @@protoc_insertion_point(field_mutable:telemetry.TelemetryRecord.feedback)
  return _internal_mutable_feedback();
}
inline void TelemetryRecord::set_allocated_feedback(::telemetry::Feedback* feedback) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete feedback_;
  }
  if (feedback) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(feedback);
    if (message_arena != submessage_arena) {
      feedback = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, feedback, submessage_arena);
    }
    
  } else {
    
  }
  feedback_ = feedback;
  // @@protoc_insertion_point(field_set_allocated:telemetry.TelemetryRecord.feedback)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace telemetry

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_telemetry_2eproto
